name: API Testing Suite

# This defines when the environment is spun up
on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows manual trigger for testing
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run API Tests
        env:
          # This maps the Vault name to a temporary variable the runner can use
          SECRET_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          SECRET_PASS: ${{ secrets.ADMIN_PASSWORD }}
          SECRET_GROUP: ${{ secrets.GROUP_ID }}
        run: |
          mvn test \
            -Dtest=Basic.userRegistration \
            -Dadmin.email=$SECRET_EMAIL \
            -Dadmin.password=$SECRET_PASS \
            -Dgroup.id=$SECRET_GROUP

